name: Tanketrommel
favicon: null
layout_spectrum: 0.9000288324896246
typography_spectrum: 0.1826478976290673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7724712500348687
  lightness: 0.22963288193568587
  saturation: 0.2355486152227968
  rhythmicContrast: 0.9890218637883663
purpose: []
