name: Tanketrommel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35278
title: Alexanders tanketrommel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c6c83'
    - '#050706'
    - '#f3f5f2'
    - '#c3d4e8'
    - '#b4a48d'
  brandStrength: 0.7724712500348687
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
